version: '3.8'
services:
  backend:
    build: ./backnend
    ports:
      -"4000:4000"
    env-file:
      - ./backend/.env
    depends_on:
      - frontend
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env-file:
      - ./frontend/.env